export default {
  login: "zhengping97",
  id: 36413759,
  node_id: "MDQ6VXNlcjM2NDEzNzU5",
  avatar_url: "https://avatars.githubusercontent.com/u/36413759?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/zhengping97",
  html_url: "https://github.com/zhengping97",
  followers_url: "https://api.github.com/users/zhengping97/followers",
  following_url: "https://api.github.com/users/zhengping97/following{/other_user}",
  gists_url: "https://api.github.com/users/zhengping97/gists{/gist_id}",
  starred_url: "https://api.github.com/users/zhengping97/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/zhengping97/subscriptions",
  organizations_url: "https://api.github.com/users/zhengping97/orgs",
  repos_url: "https://api.github.com/users/zhengping97/repos",
  events_url: "https://api.github.com/users/zhengping97/events{/privacy}",
  received_events_url: "https://api.github.com/users/zhengping97/received_events",
  type: "User",
  site_admin: false,
  name: "Heng Zheng Ping",
  company: "Nanyang Technological University",
  blog: "https://www.linkedin.com/in/hengzhengping/",
  location: "Singapore",
  email: null,
  hireable: null,
  bio: "Student",
  twitter_username: null,
  public_repos: 17,
  public_gists: 0,
  followers: 0,
  following: 0,
  created_at: "2018-02-12T15:19:09Z",
  updated_at: "2022-05-10T04:39:00Z"
}